FROM python:3.11-slim AS python_runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /build
COPY requirements.txt /build/requirements.txt
RUN pip install --no-cache-dir -r /build/requirements.txt

FROM postgres:16

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_ENV=production \
    SYSTEM_MODE=automatic_live_trading \
    RUN_MODE=live_trading \
    ARENA_GO_SANDBOX=true \
    ARENA_GO_SHORTS_ALLOWED=false \
    DECISION_ALLOW_SHORT_SELLING=false \
    DECISION_USE_POST_COST_EDGE_FOR_ACTIONS=true \
    DECISION_EXIT_USE_POST_COST_EDGE=true \
    DECISION_PARTIAL_TAKE_PROFIT_ENABLED=true \
    DECISION_PROFIT_LOCK_ENABLED=true \
    DECISION_SHORT_USE_POST_COST_EDGE=true \
    DECISION_ACTION_THRESHOLD=0.012 \
    DECISION_MIN_POST_COST_EDGE_SCORE=0.012 \
    DECISION_MACRO_EDGE_PENALTY_CAP=0.006 \
    DECISION_SHORT_ENTRY_THRESHOLD=0.012 \
    DECISION_SHORT_ADD_THRESHOLD=0.018 \
    DECISION_ALLOW_LONG_TO_SHORT_FLIP=false \
    DECISION_MIN_TARGET_POSITION_PCT=0.012 \
    DECISION_TARGET_FULL_EDGE_SCORE=0.18 \
    DECISION_MACRO_DEGRADED_EDGE_PENALTY=0.0 \
    DECISION_MACRO_OVERLAY_SHORT_BIAS_ENABLED=false \
    RISK_MIN_LOT_ROUND_UP_EDGE_AFTER_COST_FLOOR=0.012 \
    SAFE_LIVE_SUBMIT=false \
    LIVE_READINESS_PASSED=false \
    ALLOW_ARENA_GO_TOKEN_FALLBACK=false \
    SINGLE_SCHEDULER_INSTANCE=true \
    MARKET_SESSION_SOURCE=auto \
    ARENA_GO_SESSION_PROBE_ENABLED=true \
    ARENA_GO_SESSION_PROBE_REQUIRED_FOR_OPEN=true \
    ARENA_GO_SESSION_PROBE_INTERVAL_SECONDS=120 \
    ARENA_GO_SESSION_PROBE_MAX_AGE_SECONDS=300 \
    ARENA_GO_SESSION_PROBE_REQUIRE_POSITIONS=true \
    ARENA_GO_MARKET_CLOSED_COOLDOWN_SECONDS=180 \
    ARENA_GO_MARKET_TIMEZONE=Europe/Moscow \
    ARENA_GO_MARKET_EXTENDED_SESSION=true \
    ARENA_GO_MARKET_OPEN_TIME=10:00 \
    ARENA_GO_MARKET_CLOSE_TIME=23:50 \
    ALLOW_ARENA_GO_EXTENDED_MARKET_DATA_GRACE=true \
    ARENA_GO_EXTENDED_MARKET_DATA_GRACE_SECONDS=21600 \
    ARENA_GO_EXTENDED_LOOKBACK_MINUTES=480 \
    LLM_ENABLED=true \
    ENABLE_LLM_TEXT_SCHEDULES=true \
    LLM_MAX_ITEMS_PER_RUN=5 \
    LLM_MAX_CALLS_PER_MINUTE=6 \
    LLM_MAX_CALLS_PER_HOUR=120 \
    LLM_MAX_CALLS_PER_DAY=1000 \
    LLM_MIN_SECONDS_BETWEEN_CALLS=1 \
    EVENT_NEWS_DISCOVERY_INTERVAL_SECONDS=120 \
    EVENT_NEWS_FAST_INTERVAL_SECONDS=120 \
    EVENT_NEWS_MAX_ITEMS_PER_RUN=5 \
    EVENT_NEWS_ONLY_UNPROCESSED_RAW_TEXT=true \
    EVENT_NEWS_FAST_FIRST=true \
    EVENT_NEWS_REASONING_ESCALATION_ENABLED=true \
    EVENT_NEWS_ESCALATE_MATERIALITY_THRESHOLD=0.70 \
    EVENT_NEWS_ESCALATE_SENTIMENT_ABS_THRESHOLD=0.65 \
    DATA_DIR=/data \
    POSTGRES_DB=moex_agent \
    POSTGRES_USER=moex_agent \
    PGPORT=5432 \
    SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    SSL_CERT_DIR=/etc/ssl/certs

COPY --from=python_runtime /usr/local /usr/local
COPY --from=python_runtime /etc/ssl/certs /etc/ssl/certs

WORKDIR /app
COPY agent_app /app/agent_app
COPY scripts /app/scripts
RUN find /app/scripts -type f -name "*.sh" -exec sed -i 's/\r$//' {} \; \
    && find /app/scripts -type f -name "*.sh" -exec chmod +x {} \;

VOLUME ["/data"]

ENTRYPOINT ["/app/scripts/start_autonomous.sh"]
