"""Decision Engine Module implementation."""

from .metrics import (
    data_quality_penalty,
    decision_confidence_score,
    expected_edge_score,
    feature_contribution,
    portfolio_concentration_risk,
    target_position_pct,
    target_quantity,
    threshold_margin,
    weighted_average,
)
from .repository import (
    AuditRecord,
    DecisionEngineRepository,
    DecisionExplanation,
    DecisionRecord,
    DecisionRequestRecord,
    DecisionSetRecord,
    FeatureVector,
    InMemoryDecisionEngineRepository,
    MarketStateRecord,
    MetricWeightRule,
    PortfolioSnapshot,
    PositionState,
    PostgresDecisionEngineRepository,
    WeightsProfile,
)
from .service import (
    DecisionEngineError,
    DecisionEngineExecutionResult,
    DecisionEngineService,
    DecisionPolicy,
    DecisionRequest,
    InstrumentDecision,
)

__all__ = [
    "AuditRecord",
    "DecisionEngineError",
    "DecisionEngineExecutionResult",
    "DecisionEngineRepository",
    "DecisionEngineService",
    "DecisionExplanation",
    "DecisionPolicy",
    "DecisionRecord",
    "DecisionRequest",
    "DecisionRequestRecord",
    "DecisionSetRecord",
    "FeatureVector",
    "InMemoryDecisionEngineRepository",
    "InstrumentDecision",
    "MarketStateRecord",
    "MetricWeightRule",
    "PortfolioSnapshot",
    "PositionState",
    "PostgresDecisionEngineRepository",
    "WeightsProfile",
    "data_quality_penalty",
    "decision_confidence_score",
    "expected_edge_score",
    "feature_contribution",
    "portfolio_concentration_risk",
    "target_position_pct",
    "target_quantity",
    "threshold_margin",
    "weighted_average",
]
