"""Execution Engine Module implementation."""

from .gateway import ExecutionGateway, GatewayUnavailableError, submit_via_gateway
from .metrics import (
    arena_go_quantity,
    avg_fill_price,
    cancelled_order_count,
    fee_estimate,
    fill_ratio,
    partial_fill_ratio,
    rejected_order_count,
    slippage_bps,
    submitted_order_count,
    time_to_fill_ms,
)
from .repository import (
    AuditRecord,
    ExecutionEngineRepository,
    ExecutionResultRecord,
    FillReportRecord,
    InMemoryExecutionEngineRepository,
    InstrumentProfileRecord,
    OrderIntentRecord,
    OrderStatusRecord,
    PortfolioSnapshotRecord,
    PostgresExecutionEngineRepository,
    RiskCheckResultRecord,
)
from .service import (
    ExecutionEngineError,
    ExecutionEngineRunResult,
    ExecutionEngineService,
    ExecutionPolicy,
    ExecutionRequest,
    OrderExecutionOutcome,
)

__all__ = [
    "AuditRecord",
    "ExecutionEngineError",
    "ExecutionEngineRepository",
    "ExecutionEngineRunResult",
    "ExecutionEngineService",
    "ExecutionGateway",
    "ExecutionPolicy",
    "ExecutionRequest",
    "ExecutionResultRecord",
    "FillReportRecord",
    "GatewayUnavailableError",
    "InMemoryExecutionEngineRepository",
    "InstrumentProfileRecord",
    "OrderExecutionOutcome",
    "OrderIntentRecord",
    "OrderStatusRecord",
    "PortfolioSnapshotRecord",
    "PostgresExecutionEngineRepository",
    "RiskCheckResultRecord",
    "arena_go_quantity",
    "avg_fill_price",
    "cancelled_order_count",
    "fee_estimate",
    "fill_ratio",
    "partial_fill_ratio",
    "rejected_order_count",
    "slippage_bps",
    "submit_via_gateway",
    "submitted_order_count",
    "time_to_fill_ms",
]
